// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuantityMeasurementAppRepositories.Context;

#nullable disable

namespace QuantityMeasurementAppRepositories.Migrations
{
    [DbContext(typeof(DatabaseAppContext))]
    partial class DatabaseAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuantityMeasurementAppModels.Entities.PersonEntity", b =>
                {
                    b.Property<long>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EntityId"));

                    b.Property<DateTime>("EntityCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_entity_at");

                    b.Property<string>("EntityEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("entity_email");

                    b.Property<string>("EntityHashPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_password_hash");

                    b.Property<DateTime>("EntityLastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("entity_name");

                    b.HasKey("EntityId");

                    b.HasIndex("EntityEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email");

                    b.ToTable("users_authenication_and_authorization", (string)null);
                });

            modelBuilder.Entity("QuantityMeasurementAppModels.Entities.QuantityEntity", b =>
                {
                    b.Property<long>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EntityId"));

                    b.Property<DateTime>("EntityCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entity_created_at");

                    b.Property<string>("EntityErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("entity_error_message");

                    b.Property<string>("EntityFirstUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_first_unit");

                    b.Property<double>("EntityFirstValue")
                        .HasColumnType("double precision")
                        .HasColumnName("entity_first_value");

                    b.Property<string>("EntityMeasurementType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_measurement_type");

                    b.Property<string>("EntityOperation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_operation");

                    b.Property<double>("EntityResultValue")
                        .HasColumnType("double precision")
                        .HasColumnName("entity_result_value");

                    b.Property<string>("EntitySecondUnit")
                        .HasColumnType("text")
                        .HasColumnName("entity_second_unit");

                    b.Property<double>("EntitySecondValue")
                        .HasMaxLength(50)
                        .HasColumnType("double precision")
                        .HasColumnName("entity_second_value");

                    b.Property<DateTime>("EntityUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entity_updated_at");

                    b.Property<long>("EntityUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_user_id");

                    b.Property<bool>("IsEntityError")
                        .HasColumnType("boolean")
                        .HasColumnName("entity_is_error");

                    b.HasKey("EntityId");

                    b.HasIndex("EntityMeasurementType")
                        .HasDatabaseName("IX_quantity_measurements_measurement_type");

                    b.HasIndex("EntityOperation")
                        .HasDatabaseName("IX_quantity_measurements_operation");

                    b.HasIndex("EntityUserId")
                        .HasDatabaseName("IX_quantity_measurements_user_id");

                    b.HasIndex("IsEntityError")
                        .HasDatabaseName("IX_quantity_measurements_is_error");

                    b.ToTable("quantity_measurements_tables_conversion", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
